# Generated by Django 3.2.16 on 2023-01-13 23:05

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertiser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(blank=True, max_length=256)),
                ('is_comment', models.BooleanField(default=False)),
                ('is_quote_tweet', models.BooleanField(default=False)),
                ('is_commercial', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('dob', models.DateField()),
                ('country', models.CharField(default='USA', max_length=30)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('is_account_private', models.BooleanField(default=False)),
                ('is_sub_blue', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_affiliated', models.BooleanField(default=False)),
                ('bookmarks', models.ManyToManyField(related_name='user_bookmark', to='twitter_web.Tweet')),
                ('followers', models.ManyToManyField(blank=True, default=None, related_name='followings', to='twitter_web.User')),
            ],
        ),
        migrations.CreateModel(
            name='TweetImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='tweet_image')),
                ('tweet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tweet_image_user_id', to='twitter_web.tweet')),
            ],
        ),
        migrations.AddField(
            model_name='tweet',
            name='likes',
            field=models.ManyToManyField(blank=True, default=None, related_name='liked_by_users', to='twitter_web.User'),
        ),
        migrations.AddField(
            model_name='tweet',
            name='retweets',
            field=models.ManyToManyField(blank=True, default=None, related_name='retweeted_by_users', to='twitter_web.User'),
        ),
        migrations.AddField(
            model_name='tweet',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tweet_user_id', to='twitter_web.user'),
        ),
        migrations.CreateModel(
            name='Retweet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retweet_post_id', to='twitter_web.tweet')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retweet_user_id', to='twitter_web.user')),
            ],
        ),
        migrations.CreateModel(
            name='QuoteTweet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('actual_tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_tweet', to='twitter_web.tweet')),
                ('quoted_tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quoted_tweet', to='twitter_web.tweet')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='profile_image')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_image_user', to='twitter_web.user')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('1', 'Like'), ('2', 'Retweet'), ('3', 'Comment')], default='1', max_length=20)),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_on_post', to='twitter_web.tweet')),
                ('user_to_notify', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_to_notify', to='twitter_web.user')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=1024)),
                ('read_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_conversation', to='twitter_web.conversation')),
                ('receiver', models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='message_conversation_receiver', to='twitter_web.user')),
                ('sender', models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, related_name='message_conversation_sender', to='twitter_web.user')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_post_id', to='twitter_web.tweet')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_user_id', to='twitter_web.user')),
            ],
        ),
        migrations.CreateModel(
            name='Impression',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impression_post_id', to='twitter_web.tweet')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impression_user_id', to='twitter_web.user')),
            ],
        ),
        migrations.CreateModel(
            name='HeaderImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='header_image')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twitter_web.user')),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('followee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followee_id', to='twitter_web.user')),
                ('follower_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_id', to='twitter_web.user')),
            ],
        ),
        migrations.AddField(
            model_name='conversation',
            name='initiator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_sender', to='twitter_web.user'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='messages',
            field=models.ManyToManyField(blank=True, default=None, related_name='conversation_messages', to='twitter_web.Message'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_receiver', to='twitter_web.user'),
        ),
        migrations.CreateModel(
            name='CommentTweet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('comment_tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_tweet', to='twitter_web.tweet')),
                ('parent_tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_tweet', to='twitter_web.tweet')),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cost', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('advertiser_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_advertiser_id', to='twitter_web.advertiser')),
                ('tweet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_tweet_id', to='twitter_web.tweet')),
            ],
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmark_post_id', to='twitter_web.tweet')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmark_user_id', to='twitter_web.user')),
            ],
        ),
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(blank=True, default='', max_length=256)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bio_user', to='twitter_web.user')),
            ],
        ),
        migrations.AddField(
            model_name='advertiser',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertiser_id', to='twitter_web.user'),
        ),
    ]
