# Generated by Django 4.1.4 on 2022-12-29 06:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
                ('password', models.CharField(max_length=256)),
                ('dob', models.DateField()),
                ('phone', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('is_account_private', models.BooleanField(default=False)),
                ('is_sub_blue', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_affiliated', models.BooleanField(default=False)),
            ],
        ),
    ]
