# Generated by Django 4.1.4 on 2022-12-30 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_web', '0002_alter_user_country_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
