# Generated by Django 3.2.16 on 2023-01-05 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_web', '0005_headerimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('1', 'Like'), ('2', 'Retweet'), ('3', 'Comment')], default='1', max_length=20)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_on_post', to='twitter_web.tweet')),
                ('user_to_notify', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_to_notify', to='twitter_web.user')),
            ],
        ),
    ]
