# Generated by Django 3.2.16 on 2023-01-06 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_web', '0006_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='is_quote_tweet',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='text',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.CreateModel(
            name='QuoteTweet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('actual_tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_tweet', to='twitter_web.tweet')),
                ('quoted_tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quoted_tweet', to='twitter_web.tweet')),
            ],
        ),
        migrations.CreateModel(
            name='CommentTweet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comment_tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_tweet', to='twitter_web.tweet')),
                ('parent_tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_tweet', to='twitter_web.tweet')),
            ],
        ),
    ]
