# Generated by Django 3.2.16 on 2023-01-06 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_web', '0007_auto_20230106_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileimage',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_image_user', to='twitter_web.user'),
        ),
    ]
