# Generated by Django 3.2.16 on 2023-01-07 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_web', '0008_alter_profileimage_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='likes',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='liked_by_users', to='twitter_web.User'),
        ),
        migrations.AddField(
            model_name='tweet',
            name='retweets',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='retweeted_by_users', to='twitter_web.User'),
        ),
    ]
