# Generated by Django 3.2.16 on 2023-01-08 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_web', '0010_auto_20230108_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='likes',
            field=models.ManyToManyField(blank=True, default=None, related_name='liked_by_users', to='twitter_web.User'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='retweets',
            field=models.ManyToManyField(blank=True, default=None, related_name='retweeted_by_users', to='twitter_web.User'),
        ),
    ]
