# Generated by Django 3.2.16 on 2023-01-09 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_web', '0014_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(blank=True, default=None, related_name='_twitter_web_user_followers_+', to='twitter_web.User'),
        ),
        migrations.AddField(
            model_name='user',
            name='followings',
            field=models.ManyToManyField(blank=True, default=None, related_name='_twitter_web_user_followings_+', to='twitter_web.User'),
        ),
    ]
