# Generated by Django 3.2.16 on 2023-01-09 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_web', '0015_auto_20230109_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bio_user', to='twitter_web.user'),
        ),
    ]
