# Generated by Django 3.2.16 on 2023-01-09 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_web', '0016_alter_bio_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bookmarks',
            field=models.ManyToManyField(related_name='user_bookmark', to='twitter_web.Tweet'),
        ),
    ]
