# Generated by Django 3.2.16 on 2023-01-10 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_web', '0017_user_bookmarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='read_status',
            field=models.BooleanField(default=False),
        ),
    ]
