# Generated by Django 3.2.16 on 2023-01-10 05:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_web', '0018_message_read_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='receiver_id',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender_id',
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_sender', to='twitter_web.user')),
                ('messages', models.ManyToManyField(blank=True, default=None, related_name='conversation_messages', to='twitter_web.Message')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_receiver', to='twitter_web.user')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='messages_conversation', to='twitter_web.conversation'),
            preserve_default=False,
        ),
    ]
