# Generated by Django 3.2.16 on 2023-01-10 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_web', '0020_auto_20230110_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='receiver',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='message_conversation_receiver', to='twitter_web.user'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, related_name='message_conversation_sender', to='twitter_web.user'),
        ),
    ]
